name = "monolito-base"
main = "node_modules/wrangler-pages-template-worker/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "yarn install && yarn build"
output_dir = "dist"

[build.upload]
format = "service-worker"
